In [1]:
import numpy as np
a = np.empty([2, 2], dtype=int)
print(a)

[[2183571682160 2183675044576]
 [2183675533456             0]]


In [3]:
a = np.zeros([2, 2], dtype=int)


In [6]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
subtract = a - b
multiply = a * b
division = a / b
print(subtract)
print(multiply)
print(division)

[ 3 67  3 70]
[  10  360  130 3000]
[ 2.5        14.4         1.3         3.33333333]


In [7]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# slicing an array 
print(a[0 : 2])

[0 1]


In [16]:
k = np.array([3, 3, 8])
print(k)

[3 3 8]


In [21]:
k.reshape(3, 1)

array([[3],
       [3],
       [8]])

In [24]:
import pandas as pd
df = pd.DataFrame()
print(df)

lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(lst, columns=['Words'])
print(df)

Empty DataFrame
Columns: []
Index: []
    Words
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [1]:
# import seaborn as sns
# sns.load_dataset('iris')
# df = pd.read_csv("iris.csv")